application: ijoratj
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest